# Generated by Django 3.1.5 on 2021-02-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0018_auto_20200714_1832'),
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(default='', help_text='Science Tag', verbose_name='Science Tag')),
                ('userid', models.CharField(blank=True, default='', help_text='ID of user who created this tag', max_length=100, null=True, verbose_name='User ID')),
            ],
            options={
                'get_latest_by': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='tnstarget',
            options={'get_latest_by': ('-name',), 'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='TargetTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.sciencetags')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target')),
            ],
        ),
        migrations.CreateModel(
            name='ReducedDatumExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='', help_text='Type of data (either photometry or spectroscopy)', max_length=100, verbose_name='Data Type')),
                ('key', models.CharField(default='', help_text='Keyword for information being stored', max_length=200, verbose_name='Key')),
                ('value', models.TextField(blank=True, default='', help_text='String value of the information being stored', verbose_name='Value')),
                ('float_value', models.FloatField(blank=True, help_text='Float value of the information being stored, if applicable', null=True, verbose_name='Float Value')),
                ('bool_value', models.BooleanField(blank=True, help_text='Boolean value of the information being stored, if applicable', null=True, verbose_name='Boolean Value')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target')),
            ],
            options={
                'get_latest_by': 'id,',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(default='', help_text='First name of the first author', max_length=20, verbose_name='First Author First Name')),
                ('author_last_name', models.CharField(default='', help_text='Last name of the first author', max_length=20, verbose_name='First Author Last Name')),
                ('description', models.TextField(default='', help_text='Brief description of the contents of the paper', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('in prep', 'In Prep'), ('submitted', 'Submitted'), ('published', 'Published')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target')),
            ],
            options={
                'get_latest_by': ('id',),
            },
        ),
    ]
