# Generated by Django 3.1.5 on 2021-02-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0002_auto_20210202_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TNSTarget',
        ),
    ]
