# Generated by Django 3.1.5 on 2021-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_delete_tnstarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='value',
            field=models.JSONField(blank=True, help_text='String value of the information being stored', verbose_name='Value'),
        ),
    ]
